---
title: "alpha diversity"
author: "Cameron Strachan"
date: '2019-03-14'
output:
  pdf_document: default
  html_document: default
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library("ggpubr")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
shannon <- read.delim("~/master/wolf/notebooks/alpha_diversity/shannon.tsv", comment.char="#")
colnames(shannon)[13] <- 'index'
shannon$index_type <- 'shannon'

simpson <- read.delim("~/master/wolf/notebooks/alpha_diversity/simpson.tsv", comment.char="#")
colnames(simpson)[13] <- 'index'
simpson$index_type <- 'simpson'

chao1 <- read.delim("~/master/wolf/notebooks/alpha_diversity/chao1.tsv", comment.char="#")
colnames(chao1)[13] <- 'index'
chao1$index_type <- 'chao1'

df_div <- bind_rows(shannon, simpson, chao1) %>%
  separate(Identifier, into = c("species", "sample"), remove = FALSE) %>%
  filter(species != "H") %>%
  filter(sample == "S")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_div_1 <- df_div %>%
  filter(index_type == 'shannon')

p <- ggboxplot(df_div_1, x = "Identifier", y = "index",
                color = "Identifier", palette =c("#00AFBB", "#E7B800", "#FC4E07"),
                add = "jitter",  facet.by = "index_type")
p
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_div_3 <- df_div %>%
  filter(index_type == 'chao1')

p <- ggboxplot(df_div_3, x = "Identifier", y = "index",
                color = "Identifier", palette =c("#00AFBB", "#E7B800", "#FC4E07"),
                add = "jitter",  facet.by = "index_type")
p
```
