---
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(printr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(knitr)
library(gmodels)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_meta <- read.csv("~/master/wolf/dataflow/00-meta-merge/sample-complete-contact-regrouping.csv")

df_meta$SampleID <- as.character(df_meta$SampleID)
df_meta$Sample <- as.character(df_meta$Sample)
df_meta$Contact_regrouping <- as.character(df_meta$Contact_regrouping)

colnames(df_meta) <- c("sra_accession", "sample", "pack")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load combined taxonomy
df_phlycounts_tax  <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/taxonomy-no-contam.tsv", sep = '\t')
df_phlycounts_tax$Confidence <- NULL
colnames(df_phlycounts_tax)[1] <- 'asv_id'
df_phlycounts_tax$Taxon <- gsub("D_.__", "", df_phlycounts_tax$Taxon)

df_phlycounts_tax <- df_phlycounts_tax %>%
  separate(Taxon , into = c("domain", "phylum", "class", "order", "family", "genus", "species"), sep = ";")

df_phlycounts_tax$phylum <- as.character(df_phlycounts_tax$phylum)
df_phlycounts_tax$family <- as.character(df_phlycounts_tax$family)
df_phlycounts_tax$class<- as.character(df_phlycounts_tax$class)
df_phlycounts_tax$order <- as.character(df_phlycounts_tax$order)
df_phlycounts_tax$genus <- as.character(df_phlycounts_tax$genus)
df_phlycounts_tax$species <- as.character(df_phlycounts_tax$species)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/feature-table-97-no-contam.txt", sep = '\t', skip = 1)
colnames(df)[1] <- "asv_id"

df <- df %>%
  select(asv_id, starts_with("H")) %>%
  select(asv_id, ends_with("s"))

col_to_gather <- names(df)[!(startsWith(names(df), "H"))]
df <- melt(df, id = col_to_gather)
colnames(df)[2:3] <- c('sra_accession', 'count')

df$asv_id <- as.character(df$asv_id)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_normalization <- df %>%
  group_by(sra_accession) %>%
  mutate(total_reads = sum(count)) %>%
  ungroup() %>%
  select(sra_accession, total_reads) %>%
  ungroup() %>%
  distinct() 

df_classification <- df_phlycounts_tax %>%
  select(asv_id, phylum, family, genus)


df_complete <- inner_join(df, df_meta) %>%
  inner_join(df_normalization) %>%
  inner_join(df_classification)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_complete$sample_id <- df_complete$sra_accession

df_metrics <- df_complete %>% 

  mutate(count_norm = (count / total_reads)*100) %>%
  
  group_by(sample_id, asv_id) %>%
  
  mutate(count_norm = median(count_norm)) %>%
  
  ungroup() %>%
  
  unite(classification, c("phylum", "family", "genus"), sep = ";", remove = FALSE) %>%
  
  select(-sra_accession) %>%
  
  distinct() %>%
  
  rowwise() %>%
  
  mutate(above_0 = ifelse(count_norm != 0, 1, 0)) %>%
  
  group_by(pack, sample) %>%
  
  mutate(npack = length(unique(sample_id))) %>%
  
  ungroup() %>%
  
  filter(npack > 2) %>%
  
  group_by(asv_id, sample) %>%
  
  mutate(nsamples = sum(above_0)) %>% 
           
  ungroup() %>%
  
  filter(nsamples > 2) %>%
  
  group_by(asv_id, pack) %>%
  
  mutate(contains_0 = ifelse(0 %in% above_0, 0, 1)) %>%
  
  ungroup() %>%
  
  group_by(asv_id) %>%
  
  mutate(all_contains_0 = ifelse(sum(contains_0) == 0, TRUE, FALSE)) %>%
  
  ungroup() %>%
  
  filter(all_contains_0 == FALSE)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_phlycounts_counts <- df_metrics %>%
  select(asv_id, sample_id, count) %>%
  spread(sample_id, count)

df_phlycounts_counts[is.na(df_phlycounts_counts)] <- 0

df_phlycounts_counts <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] 

numsamples <- length(df_phlycounts_counts)

otumat <- as.matrix(df_phlycounts_counts[,2:numsamples])
rownames(otumat) <- as.data.frame(df_phlycounts_counts)[,1]

df_phlycounts_tax <- df_metrics %>%
  select(asv_id, phylum, family, genus) %>%
  unique()

df_phlycounts_tax$phylum <- as.character(df_phlycounts_tax$phylum)
df_phlycounts_tax$family <- as.character(df_phlycounts_tax$family)
df_phlycounts_tax$genus <- as.character(df_phlycounts_tax$genus)

df_phlycounts_tax[is.na(df_phlycounts_tax)] <- "NotAssigned"

df_phlycounts_tax <- df_phlycounts_tax[order(df_phlycounts_tax$asv_id),] 

taxmat <- as.matrix(df_phlycounts_tax[,2:4])
rownames(taxmat) <- as.data.frame(df_phlycounts_tax)[,1]

df_phylocounts_meta <- df_metrics %>% 
  select(sample_id, sample, pack) %>%
  unique() %>%
  rowwise() %>%
  ungroup()

df_phylocounts_meta$sample <- as.factor(df_phylocounts_meta$sample)
df_phylocounts_meta$pack <- as.factor(df_phylocounts_meta$pack)


df_phylocounts_meta <- as.data.frame(df_phylocounts_meta)

row.names(df_phylocounts_meta) <- df_phylocounts_meta[,1]
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=20, fig.height=25}
library("phyloseq")
library("ape")
library("DESeq2")

OTU = otu_table(otumat, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)
physeq = phyloseq(OTU, TAX)

#fast_tree = read.tree("~/master/wolf/dataflow/02-trees/wetzels2018-8_270_8_220-97.out")
#random_tree = rtree(ntaxa(physeq), rooted=TRUE, tip.label=taxa_names(physeq))

samplesdata <- sample_data(df_phylocounts_meta)

physeq = phyloseq(OTU, TAX, samplesdata)



diagdds = phyloseq_to_deseq2(physeq, ~ pack)

# calculate geometric means prior to estimate size factors
#gm_mean = function(x, na.rm=TRUE){
#  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
#}

#geoMeans = apply(counts(diagdds), 1, gm_mean)
#diagdds = estimateSizeFactors(diagdds, geoMeans = geoMeans)

diagdds = DESeq(diagdds, fitType = "parametric", test = "Wald")

res = results(diagdds, cooksCutoff = FALSE)
alpha = 0.05
sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(physeq)[rownames(sigtab), ], "matrix"))

selected_seq_ids <- row.names(sigtab)

df_plot <- df_metrics[df_metrics$asv_id %in% selected_seq_ids,]

# ggplot(df_plot, aes(x=pack, y=count)) + 
#             geom_point(aes(colour = pack), size = 5) + 
#   facet_wrap( ~ asv_id, scales="free") +
#   theme() +
#           theme(strip.text = element_text(size = 12),
#           plot.title = element_text(size = 30),
#           axis.text.x = element_text(angle = 90, hjust = 1, size = 20),
#           axis.text.y = element_text(size = 20),
#           axis.title.x = element_text(size = 20),
#           axis.title.y = element_text(size = 20))
```

\newpage

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=20, fig.height=25}
# ggplot(df_plot, aes(x=pack, y=count_norm)) + 
#             geom_point(aes(colour = pack), size = 5) + 
#   facet_wrap( ~ genus, scales="free") +
#           theme(strip.text = element_text(size = 20),
#           plot.title = element_text(size = 30),
#           axis.text.x = element_text(angle = 90, hjust = 1, size = 20),
#           axis.text.y = element_text(size = 20),
#           axis.title.x = element_text(size = 20),
#           axis.title.y = element_text(size = 20))
```

\vspace{12pt}
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=9, fig.height=7}
seq_id <- as.data.frame(cbind(unique(df_plot$asv_id), seq(1, length(unique(df_plot$asv_id)), 1)))
colnames(seq_id) <- c("asv_id", "seq_num")

colnames(df_plot)[4] <- "contact"

df_plot <- df_plot %>%
  inner_join(seq_id) %>%
  unite(ID, c("genus", "seq_num"), sep = " ") %>%
  filter(ID != "NA 6") %>%
  filter(ID != "NA 7") 

library(ggpubr)
ggboxplot(df_plot, x = "contact", y = "count_norm",
                color = "contact", palette =c("#00AFBB", "#E7B800", "#FC4E07"),
                add = "jitter") +
  facet_wrap( ~ ID, scales="free") +
  ylab("Relative Abundance") + 
  xlab("Contact")
```