---
title: "tSNE plots"
author: "Cameron Strachan"
date: '2019-03-14'
output:
  pdf_document: default
  html_document: default
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load meta data that specifies control data
df_phylocounts_meta <- read.csv("~/master/wolf/dataflow/00-meta-merge/sample-metadata-sub.csv")

df_phylocounts_meta <- as.data.frame(df_phylocounts_meta)
row.names(df_phylocounts_meta) <- df_phylocounts_meta[,1]
df_phylocounts_meta[,1] <- NULL

df_phylocounts_meta$SampleID <- rownames(df_phylocounts_meta)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load feature table with both control and normal sampes
df_phlycounts_counts <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/feature-table-97-no-contam.txt", sep = '\t', skip = 1)
colnames(df_phlycounts_counts)[1] <- "asv_id"

df_phlycounts_counts <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] 

numsamples <- length(df_phlycounts_counts)

otumat <- as.matrix(df_phlycounts_counts[,2:numsamples])
rownames(otumat) <- as.data.frame(df_phlycounts_counts)[,1]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load feature table with both control and normal sampes
df_phlycounts_counts <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/feature-table-97-no-contam.txt", sep = '\t', skip = 1)
colnames(df_phlycounts_counts)[1] <- "asv_id"

df_phlycounts_counts_wp <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] %>%
  select(starts_with("D"), starts_with("W"), asv_id) %>%
  select(-starts_with("W9f"), -starts_with("D15f"), -starts_with("D2f"), -starts_with("D14f"), -starts_with("D13f"), -starts_with("D1f"), -starts_with("W4f"), -starts_with("W13f"), -starts_with("W16f"), -starts_with("W1f"), -starts_with("W14f"), -starts_with("W3f")) %>%
  select(asv_id, ends_with("f"))

numsamples <- length(df_phlycounts_counts_wp)

otumatwpf <- as.matrix(df_phlycounts_counts_wp[,2:numsamples])
rownames(otumatwpf) <- as.data.frame(df_phlycounts_counts_wp)[,1]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load feature table with both control and normal sampes
df_phlycounts_counts <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/feature-table-97-no-contam.txt", sep = '\t', skip = 1)
colnames(df_phlycounts_counts)[1] <- "asv_id"

df_phlycounts_counts_wp <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] %>%
  select(starts_with("D"), starts_with("W"), asv_id) %>%
  select(-starts_with("W9s"), -starts_with("D15s"), -starts_with("D2s"), -starts_with("D14s"), -starts_with("D13s"), -starts_with("D1s"), -starts_with("W4s"), -starts_with("W13s"), -starts_with("W16s"), -starts_with("W1s"), -starts_with("W14s"), -starts_with("W3s")) %>%
  select(asv_id, ends_with("s"))

numsamples <- length(df_phlycounts_counts_wp)

otumatwps <- as.matrix(df_phlycounts_counts_wp[,2:numsamples])
rownames(otumatwps) <- as.data.frame(df_phlycounts_counts_wp)[,1]
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load feature table with both control and normal sampes
df_phlycounts_counts <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/feature-table-97-no-contam.txt", sep = '\t', skip = 1)
colnames(df_phlycounts_counts)[1] <- "asv_id"

df_phlycounts_counts_wp <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] %>%
  select(starts_with("W"), asv_id) %>%
  select(-starts_with("W9f"), -starts_with("W4f"), -starts_with("W13f"), -starts_with("W16f"), -starts_with("W1f"), -starts_with("W14f"), -starts_with("W3f")) %>%
  select(asv_id, ends_with("f"))

numsamples <- length(df_phlycounts_counts_wp)

otumatwopf <- as.matrix(df_phlycounts_counts_wp[,2:numsamples])
rownames(otumatwopf) <- as.data.frame(df_phlycounts_counts_wp)[,1]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load feature table with both control and normal sampes
df_phlycounts_counts <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/feature-table-97-no-contam.txt", sep = '\t', skip = 1)
colnames(df_phlycounts_counts)[1] <- "asv_id"

df_phlycounts_counts_wp <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] %>%
  select(starts_with("W"), asv_id) %>%
  select(-starts_with("W9s"), -starts_with("W4s"), -starts_with("W13s"), -starts_with("W16s"), -starts_with("W1s"), -starts_with("W14s"), -starts_with("W3s")) %>%
  select(asv_id, ends_with("s"))

numsamples <- length(df_phlycounts_counts_wp)

otumatwops <- as.matrix(df_phlycounts_counts_wp[,2:numsamples])
rownames(otumatwops) <- as.data.frame(df_phlycounts_counts_wp)[,1]
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# load combined taxonomy
df_phlycounts_tax  <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/taxonomy-no-contam.tsv", sep = '\t')
df_phlycounts_tax$Confidence <- NULL
colnames(df_phlycounts_tax)[1] <- 'asv_id'
df_phlycounts_tax$Taxon <- gsub("D_.__", "", df_phlycounts_tax$Taxon)

df_phlycounts_tax <- df_phlycounts_tax %>%
  separate(Taxon , into = c("domain", "phylum", "class", "order", "family", "genus", "species"), sep = ";")

df_phlycounts_tax$phylum <- as.character(df_phlycounts_tax$phylum)
df_phlycounts_tax$family <- as.character(df_phlycounts_tax$family)
df_phlycounts_tax$class<- as.character(df_phlycounts_tax$class)
df_phlycounts_tax$order <- as.character(df_phlycounts_tax$order)
df_phlycounts_tax$genus <- as.character(df_phlycounts_tax$genus)
df_phlycounts_tax$species <- as.character(df_phlycounts_tax$species)

df_phlycounts_tax[is.na(df_phlycounts_tax)] <- "NotAssigned"

df_phlycounts_tax <- df_phlycounts_tax[order(df_phlycounts_tax$asv_id),] 

numsamples2 <- length(df_phlycounts_tax)

taxmat <- as.matrix(df_phlycounts_tax[,2:numsamples2])
rownames(taxmat) <- as.data.frame(df_phlycounts_tax)[,1]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library("phyloseq")
library("ape")
library(plyr)

# import tree and load phyloseq obect

tree = read.tree("~/master/wolf/dataflow/04-tree-merge/tree-97-no-contam.nwk")

OTU = otu_table(otumat, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)

df_phylocounts_meta$SampleIDnum <- gsub("H", "", df_phylocounts_meta$SampleID)
df_phylocounts_meta$SampleIDnum <- gsub("D", "", df_phylocounts_meta$SampleIDnum)
df_phylocounts_meta$SampleIDnum <- gsub("P", "", df_phylocounts_meta$SampleIDnum)
df_phylocounts_meta$SampleIDnum <- gsub("W", "", df_phylocounts_meta$SampleIDnum)
df_phylocounts_meta$SampleIDnum <- gsub("s", "", df_phylocounts_meta$SampleIDnum)
df_phylocounts_meta$SampleIDnum <- gsub("f", "", df_phylocounts_meta$SampleIDnum)

samplesdata <- sample_data(df_phylocounts_meta)
physeq = phyloseq(OTU, TAX, samplesdata, tree)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
set.seed(2)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
# Phyloseq object with relative abundance

physeq_trim = prune_samples(sample_sums(physeq)>=14000, physeq)
physeq_trim = filter_taxa(physeq_trim, function(x) sum(x > 10) > (0.1*length(x)), TRUE)
physeq_trim_norm = transform_sample_counts(physeq_trim, function(x) sqrt(x / sum(x)))


#t-SNE plot 
library(tsnemicrobiota)

t_SNE <- tsne_phyloseq(physeq_trim_norm, distance = "bray", perplexity = 25,
  precomputed_distance = NULL, pseudocounts = 1, verbose = 1,
  rng_seed = NULL, philr_options = list(), control = list())

getPalette = colorRampPalette(brewer.pal(9, "Set1"))
colourCount = length(unique(df_phylocounts_meta$Identifier))

tsne_plot <- plot_tsne_phyloseq(physeq_trim_norm, t_SNE,
    color = 'Identifier', title='t-SNE (bray)',shape="Contact_to_WSC_animals") +
    geom_point(size=1.5)+scale_color_manual(values = getPalette(colourCount)) +
             scale_shape_manual(values=15:18)

tsne_plot
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
tsne_plot <- plot_tsne_phyloseq(physeq_trim_norm, t_SNE,
    color = 'SampleIDnum', title='t-SNE (bray)', shape = 'SampleIDnum') +
    geom_point(size=1.5) + scale_shape_manual(values=1:16)

tsne_plot
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# import tree and load phyloseq obect
OTU = otu_table(otumatwpf, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)
samplesdata <- sample_data(df_phylocounts_meta)
physeq = phyloseq(OTU, TAX, samplesdata, tree)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Phyloseq object with relative abundance
set.seed(2)
physeq_trim = prune_samples(sample_sums(physeq)>=4000, physeq)
physeq_trim = filter_taxa(physeq_trim, function(x) sum(x > 10) > (0.1*length(x)), TRUE)
physeq_trim_norm = transform_sample_counts(physeq_trim, function(x) sqrt(x / sum(x)))


#t-SNE plot 

t_SNE <- tsne_phyloseq(physeq_trim_norm, distance = "bray", perplexity = 10,
  precomputed_distance = NULL, pseudocounts = 1, verbose = 1,
  rng_seed = NULL, philr_options = list(), control = list())

getPalette = colorRampPalette(brewer.pal(9, "Set1"))
colourCount = length(unique(df_phylocounts_meta$Identifier))

tsne_plot <- plot_tsne_phyloseq(physeq_trim_norm, t_SNE,
    color = 'WildPack', title='t-SNE (bray) - Feces',shape="Identifier") +
    geom_point(size=3)+scale_color_manual(values = getPalette(colourCount)) +
             scale_shape_manual(values=15:18)

tsne_plot
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
tsne_plot <- plot_tsne_phyloseq(physeq_trim_norm, t_SNE,
    color = 'SampleIDnum', title='t-SNE (bray)', shape = 'SampleIDnum') +
    geom_point(size=1.5) + scale_shape_manual(values=1:16)

tsne_plot
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# import tree and load phyloseq obect
OTU = otu_table(otumatwps, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)
samplesdata <- sample_data(df_phylocounts_meta)
physeq = phyloseq(OTU, TAX, samplesdata, tree)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Phyloseq object with relative abundance
set.seed(2)
physeq_trim = prune_samples(sample_sums(physeq)>=4000, physeq)
physeq_trim = filter_taxa(physeq_trim, function(x) sum(x > 10) > (0.1*length(x)), TRUE)
physeq_trim_norm = transform_sample_counts(physeq_trim, function(x) sqrt(x / sum(x)))


#t-SNE plot 

t_SNE <- tsne_phyloseq(physeq_trim_norm, distance = "bray", perplexity = 10,
  precomputed_distance = NULL, pseudocounts = 1, verbose = 1,
  rng_seed = NULL, philr_options = list(), control = list())

getPalette = colorRampPalette(brewer.pal(9, "Set1"))
colourCount = length(unique(df_phylocounts_meta$Identifier))

tsne_plot <- plot_tsne_phyloseq(physeq_trim_norm, t_SNE,
    color = 'WildPack', title='t-SNE (bray) - Skin',shape="Identifier") +
    geom_point(size=1.5)+scale_color_manual(values = getPalette(colourCount)) +
             scale_shape_manual(values=15:18)

tsne_plot
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
tsne_plot <- plot_tsne_phyloseq(physeq_trim_norm, t_SNE,
    color = 'SampleIDnum', title='t-SNE (bray)', shape = 'SampleIDnum') +
    geom_point(size=1.5) + scale_shape_manual(values=1:16)

tsne_plot
```