---
output:
  pdf_document: default
  html_document: default
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(printr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(knitr)
library(pwr)
library("ggpubr")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_meta <- read.csv("~/master/wolf/dataflow/00-meta/wetzels2018_wu2018_fastq.csv")
colnames(df_meta)[1] <- "sra_accession"
df_meta$sra_accession <- as.character(df_meta$sra_accession)
df_meta$type <- as.character(df_meta$type)
df_meta$study <- as.character(df_meta$study)
df_meta$region <- as.character(df_meta$region)
df_meta$sample <- as.character(df_meta$sample)
df_meta$pack <- as.character(df_meta$pack)
df_meta$sibling <- as.character(df_meta$sibling)
df_meta$replicate <- as.character(df_meta$replicate)
df_meta$sample_id <- as.character(df_meta$sample_id)

df_classification  <- read.csv("~/master/wolf/dataflow/03-asv-taxonomy/wetzels2018-8_270_8_220-97-rdp.csv")
df_classification[,1] <- NULL

df <- read.delim("~/master/wolf/dataflow/03-asv-table/wetzels2018-8_270_8_220-97.txt", skip = 1, header = TRUE)
df$clustering <- 97

colnames(df)[1] <- 'asv_id'

col_to_gather <- names(df)[!(startsWith(names(df), "SRR") |  startsWith(names(df), "W"))]
df <- melt(df, id = col_to_gather)
colnames(df)[3:4] <- c('sra_accession', 'count')

df$asv_id <- as.character(df$asv_id)


df_normalization <- df %>%
  filter(clustering == 97) %>%
  group_by(sra_accession) %>%
  mutate(total_16s_reads = sum(count)) %>%
  ungroup() %>%
  select(sra_accession, total_16s_reads) %>%
  ungroup() %>%
  distinct() 

df_classification <- df_classification %>%
  select(asv_id, phylum, family, genus)


df_complete <- inner_join(df, df_meta) %>%
  inner_join(df_normalization) %>%
  inner_join(df_classification)

df_normalization_plot <- inner_join(df_normalization, df_meta)
```

## summary

- The Wolf skin and fecal samples (Wolf Science Centre - WSC) we're processed with dada2.
- All the data, after processing, was clustered together at 97% identity and taxonomically classified using RDB.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_metrics <- df_complete %>% 

  mutate(count_norm = (count / total_16s_reads)*100) %>%
  
  group_by(sample_id, asv_id) %>%
  
  mutate(count_norm = median(count_norm)) %>%
  
  ungroup() %>%
  
  unite(classification, c("phylum", "family", "genus"), sep = ";", remove = FALSE) %>%
  
  select(-sra_accession, -replicate, -total_16s_reads, -count) %>%
  distinct() 

df_metrics_trim <- df_metrics %>%
  filter(count_norm != 0) %>%
  group_by(asv_id) %>%
  mutate(nsamples = length(unique(sample_id))) %>%
  ungroup() %>%
  filter(nsamples > 2) %>%
  select(asv_id) %>%
  distinct()

df_metrics <- inner_join(df_metrics, df_metrics_trim)
```

\newpage

### phylum level grouping

- Skin and Fecal samples are very distinct at the phylum level. 

\vspace{12pt}

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=7}
df_metrics_phylum <- df_metrics %>%
  group_by(sample_id, phylum) %>%
  mutate(phylum_percent = sum(count_norm)) %>%
  ungroup() %>%
  select(sample_id, phylum, phylum_percent, sample) %>%
  distinct() 

ggplot() + geom_bar(
  aes(y = phylum_percent, x = sample_id, fill = phylum),
  data = df_metrics_phylum,
  stat = "identity" ,
  position = "fill"
)  +labs(x="Category" , y= "Percentage (%)")+
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 16),
        strip.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 16), 
        axis.title.y = element_text(size = 20)) + 
     facet_wrap(.~sample, scales="free")+
  ylab("Percentage of Sample") +
  xlab("Individual Sample")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_phlycounts_counts <- df_metrics %>%
  select(asv_id, sample_id, count_norm) %>%
  spread(sample_id, count_norm)

df_phlycounts_counts <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] 

otumat <- as.matrix(df_phlycounts_counts[,2:33])
rownames(otumat) <- as.data.frame(df_phlycounts_counts)[,1]

df_phlycounts_tax <- df_metrics %>%
  select(asv_id, phylum, family, genus) %>%
  unique()

df_phlycounts_tax$phylum <- as.character(df_phlycounts_tax$phylum)
df_phlycounts_tax$family <- as.character(df_phlycounts_tax$family)
df_phlycounts_tax$genus <- as.character(df_phlycounts_tax$genus)

df_phlycounts_tax[is.na(df_phlycounts_tax)] <- "NotAssigned"

df_phlycounts_tax <- df_phlycounts_tax[order(df_phlycounts_tax$asv_id),] 

taxmat <- as.matrix(df_phlycounts_tax[,2:4])
rownames(taxmat) <- as.data.frame(df_phlycounts_tax)[,1]

df_phylocounts_meta <- df_metrics %>% 
  select(sample_id, sample, pack, sibling) %>%
  unique() %>%
  rowwise() %>%
  ungroup()

df_phylocounts_meta <- as.data.frame(df_phylocounts_meta)

row.names(df_phylocounts_meta) <- df_phylocounts_meta[,1]
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=20, fig.height=8}
library("phyloseq")
library("ape")
library(plyr)
OTU = otu_table(otumat, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)
physeq = phyloseq(OTU, TAX)
fast_tree = read.tree("~/master/wolf/dataflow/02-trees/wetzels2018-8_270_8_220-97.out")
#random_tree = rtree(ntaxa(physeq), rooted=TRUE, tip.label=taxa_names(physeq))
samplesdata <- sample_data(df_phylocounts_meta)
physeq = phyloseq(OTU, TAX, samplesdata, fast_tree)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library("doParallel")
library("foreach")

unifracmaxtrix <- UniFrac(physeq, weighted=FALSE, normalized=TRUE, parallel=FALSE, fast=TRUE)
df_unifrac <- as.data.frame(as.matrix(unifracmaxtrix))

write.csv(df_unifrac, "~/master/wolf/dataflow/03-distance/unifrac_matrix_unweighted.csv")

unifracmaxtrix <- UniFrac(physeq, weighted=TRUE, normalized=TRUE, parallel=FALSE, fast=TRUE)
df_unifrac <- as.data.frame(as.matrix(unifracmaxtrix))

write.csv(df_unifrac, "~/master/wolf/dataflow/03-distance/unifrac_matrix_weighted.csv")
```


