---
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(printr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(knitr)
library(pwr)
library("ggpubr")
library(gmodels)
library(ggpubr)
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_meta <- read.csv("~/master/wolf/dataflow/00-meta-merge/wetzels2018_wu2018_fastq.csv")
colnames(df_meta)[1] <- "sra_accession"
df_meta$sra_accession <- as.character(df_meta$sra_accession)
df_meta$type <- as.character(df_meta$type)
df_meta$study <- as.character(df_meta$study)
df_meta$region <- as.character(df_meta$region)
df_meta$sample <- as.character(df_meta$sample)
df_meta$pack <- as.character(df_meta$pack)
df_meta$sibling <- as.character(df_meta$sibling)
df_meta$replicate <- as.character(df_meta$replicate)
df_meta$sample_id <- as.character(df_meta$sample_id)

df_classification  <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/wetzels2018_wu2018-97-rdp.csv")
df_classification[,1] <- NULL


df <- read.delim("~/master/wolf/dataflow/03-asv-table-merge/wetzels2018_wu2018-97.txt", skip = 1, header = TRUE)
df$clustering <- 97

colnames(df)[1] <- 'asv_id'

col_to_gather <- names(df)[!(startsWith(names(df), "SRR") |  startsWith(names(df), "W"))]
df <- melt(df, id = col_to_gather)
colnames(df)[3:4] <- c('sra_accession', 'count')

df$asv_id <- as.character(df$asv_id)


df_normalization <- df %>%
  filter(clustering == 97) %>%
  group_by(sra_accession) %>%
  mutate(total_16s_reads = sum(count)) %>%
  ungroup() %>%
  select(sra_accession, total_16s_reads) %>%
  ungroup() %>%
  distinct() 

df_classification <- df_classification %>%
  select(asv_id, phylum, family, genus)


df_complete1 <- inner_join(df, df_meta) %>%
  inner_join(df_normalization) %>%
  inner_join(df_classification) %>%
  filter(study == "wu2018")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_phlycounts_tax  <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/taxonomy-no-contam.tsv", sep = '\t')
df_phlycounts_tax$Confidence <- NULL
colnames(df_phlycounts_tax)[1] <- 'asv_id'
df_phlycounts_tax$Taxon <- gsub("D_.__", "", df_phlycounts_tax$Taxon)

df_phlycounts_tax <- df_phlycounts_tax %>%
  separate(Taxon , into = c("domain", "phylum", "class", "order", "family", "genus", "species"), sep = ";")

df_phlycounts_tax$phylum <- as.character(df_phlycounts_tax$phylum)
df_phlycounts_tax$family <- as.character(df_phlycounts_tax$family)
df_phlycounts_tax$class<- as.character(df_phlycounts_tax$class)
df_phlycounts_tax$order <- as.character(df_phlycounts_tax$order)
df_phlycounts_tax$genus <- as.character(df_phlycounts_tax$genus)
df_phlycounts_tax$species <- as.character(df_phlycounts_tax$species)

df_classification <- df_phlycounts_tax

df <- read.csv("~/master/wolf/dataflow/03-asv-table-merge/feature-table-97-no-contam.txt", sep = '\t', skip = 1)
colnames(df)[1] <- "asv_id"

df <- df %>%
  select(asv_id, starts_with("W"), starts_with("D")) %>%
  select(asv_id, ends_with("f"))

col_to_gather <- names(df)[!(startsWith(names(df), "W") | startsWith(names(df), "D"))]
df <- melt(df, id = col_to_gather)
colnames(df)[2:3] <- c('sra_accession', 'count')

df$asv_id <- as.character(df$asv_id)

df_normalization <- df %>%
  group_by(sra_accession) %>%
  mutate(total_16s_reads = sum(count)) %>%
  ungroup() %>%
  select(sra_accession, total_16s_reads) %>%
  ungroup() %>%
  distinct() 

df_classification <- df_classification %>%
  select(asv_id, phylum, family, genus)


df_complete2 <- inner_join(df, df_meta) %>%
  inner_join(df_normalization) %>%
  inner_join(df_classification)

df_complete <- bind_rows(df_complete1, df_complete2)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_metrics <- df_complete %>% 

  filter(region != "Henan") %>%
  
  mutate(count_norm = (count / total_16s_reads)*100) %>%
  
  group_by(sample_id, asv_id) %>%
  
  mutate(count_norm = median(count_norm)) %>%
  
  ungroup() %>%
  
  unite(classification, c("phylum", "family", "genus"), sep = ";", remove = FALSE) %>%
  
  select(-sra_accession, -replicate, -total_16s_reads, -count) %>%
  distinct()
```

### Figure 1. 

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=15, fig.height=7}
df_metrics_phylum <- df_metrics %>%
  filter(count_norm > 0.1) %>%
  group_by(sample_id, phylum) %>%
  mutate(phylum_percent = sum(count_norm)) %>%
  ungroup() %>%
  select(sample_id, phylum, phylum_percent, study, region, type, sample) %>%
  distinct() %>%
  group_by(phylum) %>%
  mutate(avg_phylum_percent = mean(phylum_percent)) %>%
  ungroup() %>%
  rowwise() %>%
  mutate(phylum = ifelse(avg_phylum_percent > 1, phylum, "Other"))
  

df_metrics_phylum$study2 <- gsub("2018", " et al. 2018", df_metrics_phylum$study)
df_metrics_phylum$study2 <- gsub("w", "W", df_metrics_phylum$study2)

ggplot() + geom_bar(
  aes(y = phylum_percent, x = sample_id, fill = phylum),
  data = df_metrics_phylum,
  stat = "identity" ,
  position = "fill"
)  +labs(x="Category" , y= "Percentage (%)")+
  theme_minimal() +
  theme(strip.text = element_text(size = 20),
          plot.title = element_text(size = 20),
          axis.text.x = element_text(angle = 90, hjust = 1, size = 14),
          axis.text.y = element_text(size = 14),
          axis.title.x = element_text(size = 20),
          axis.title.y = element_text(size = 20)) + 
  theme(legend.text=element_text(size=14)) +
  theme(legend.title=element_text(size=20)) +
     facet_wrap(study2~type, scales="free")+
  ylab("Percentage of Sample") +
  xlab("Individual Sample") 
```
