---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(stringi)
library(reshape2)
library(readr)
library(ggthemes)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
files <- list.files('~/master/anna/dataflow/02-blast/allvall/')
blastdir <- '~/master/anna/dataflow/02-blast/allvall/'

dflist <- list()

i <- 1
for (file in files){
  df <- read.table(paste(blastdir, file, sep = ''))
  df$file <- file
  df$V1 <- as.character(df$V1)
  df$V2 <- as.character(df$V2)
  dflist[[i]] <- df
  i <- i+1
}

df_compiled <- bind_rows(dflist)
colnames(df_compiled)[1:13] <- c("qseqid", "sseqid", "pident", "sstart", "send", "qstart", "qend", "evalue", "bitscore", "score", "qlen", "length", "sseq")

df_compiled$file <- gsub("\\.txt", "", df_compiled$file)

df_compiled <- df_compiled %>%
  separate(file, into = c("file1", "file2"), sep = "\\.") %>%
  mutate(piali = (length / qlen) * 100) %>%
  filter(piali > 40) %>%
  filter(pident > 30)


df_compiled$sseq <- NULL

df_forward <- df_compiled %>%
  select(qseqid, sseqid,file1, file2, pident) %>%
  rename(forward_pi = pident) %>%
  distinct()

df_reverse <- df_compiled %>%
  select(qseqid, sseqid, file1, file2, pident) %>%
  rename(reverse_pi = pident) %>%
  distinct()

colnames(df_reverse)[1:4] <- c("sseqid", "qseqid", "file2", "file1")

df_rbh <- inner_join(df_forward, df_reverse) %>%
  mutate(mean_pi = (forward_pi + reverse_pi)/2) %>%
  select(-forward_pi, -reverse_pi) %>%
  distinct() %>%
  rowwise() %>%
  mutate(samefile = ifelse(file1 == file2, "yes", "no")) %>%
  filter(samefile != "yes") %>%
  select(-samefile) 

df_rbh$sseqid[is.na(df_rbh$sseqid)] <- "None"
df_rbh$file1[is.na(df_rbh$file1)] <- "None"
df_rbh$file2[is.na(df_rbh$file2)] <- "None"
df_rbh$mean_pi[is.na(df_rbh$mean_pi)] <- 0.0

df_rbh$qseqid <- gsub("n_", "", df_rbh$qseqid)
df_rbh$sseqid <- gsub("n_", "", df_rbh$sseqid)

df_plot <- df_rbh %>%
  select(-file1, -file2) %>%
  separate(qseqid, into = c("genome1", "contig1", "gene1"), sep = "_", remove = FALSE) %>%
  separate(sseqid, into = c("genome2", "contig2", "gene2"), sep = "_", remove = FALSE) 

df_plot$gene1 <- as.numeric(df_plot$gene1)  
df_plot$gene2 <- as.numeric(df_plot$gene2)  

df_plot_stinki <- df_plot %>%
  filter(genome1 == "stinkeri") %>%
  arrange(gene1)

df_plot_noah <- df_plot %>%
  filter(genome1 == "noahi") %>%
  arrange(gene1)

df_plot_gracillis <- df_plot %>%
  filter(genome1 == "gracillis") %>%
  arrange(gene1)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(Biostrings)

inputFile="~/master/anna/dataflow/01-nucl/n_gracillis.fna"
outputFolder="~/master/anna/dataflow/03-tetra"

windowSize=5000
step=1000

genomeBin<-readDNAStringSet(inputFile)
baseFrequencies_1=oligonucleotideFrequency(genomeBin[[1]],width=1,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[1]])),width=1,with.labels=TRUE)
baseFrequencies_2=oligonucleotideFrequency(genomeBin[[1]],width=2,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[1]])),width=2,with.labels=TRUE)
baseFrequencies_3=oligonucleotideFrequency(genomeBin[[1]],width=3,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[1]])),width=3,with.labels=TRUE)
baseFrequencies_4=oligonucleotideFrequency(genomeBin[[1]],width=4,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[1]])),width=4,with.labels=TRUE)
if(length(genomeBin)>1){
for(i in c(2:length(genomeBin))){
	baseFrequencies_1=baseFrequencies_1+oligonucleotideFrequency(genomeBin[[i]],width=1,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=1,with.labels=TRUE)
	baseFrequencies_2=baseFrequencies_2+oligonucleotideFrequency(genomeBin[[i]],width=2,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=2,with.labels=TRUE)
	baseFrequencies_3=baseFrequencies_3+oligonucleotideFrequency(genomeBin[[i]],width=3,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=3,with.labels=TRUE)
	baseFrequencies_4=baseFrequencies_4+oligonucleotideFrequency(genomeBin[[i]],width=4,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=4,with.labels=TRUE)
}
}
oligoFreqCorMatrix=NULL
runningLength=0
for(i in c(1:length(genomeBin))){
	if(length(genomeBin[[i]])<=windowSize){
		oligoFrequencies_1=oligonucleotideFrequency(genomeBin[[i]],width=1,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=1,with.labels=TRUE)
		oligoFrequencies_2=oligonucleotideFrequency(genomeBin[[i]],width=2,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=2,with.labels=TRUE)
		oligoFrequencies_3=oligonucleotideFrequency(genomeBin[[i]],width=3,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=3,with.labels=TRUE)
		oligoFrequencies_4=oligonucleotideFrequency(genomeBin[[i]],width=4,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]])),width=4,with.labels=TRUE)
		oligoFreqCorMatrix<-rbind(oligoFreqCorMatrix,c(as.numeric(names(genomeBin)[i]),1,length(genomeBin[[i]]),length(genomeBin[[i]]),runningLength,runningLength+length(genomeBin[[i]]),cor(log10(baseFrequencies_1+1),log10(oligoFrequencies_1+1)),cor(log10(baseFrequencies_2+1),log10(oligoFrequencies_2+1)),cor(log10(baseFrequencies_3+1),log10(oligoFrequencies_3+1)),cor(log10(baseFrequencies_4+1),log10(oligoFrequencies_4+1))))
		runningLength=runningLength+length(genomeBin[[i]])
	}else{
		for(j in c(step*(c(0:floor((length(genomeBin[[i]])-windowSize+1)/step)))+1,length(genomeBin[[i]])-windowSize)){
			oligoFrequencies_1=oligonucleotideFrequency(genomeBin[[i]][j:(j+windowSize-1)],width=1,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]][j:(j+windowSize-1)])),width=1,with.labels=TRUE)
			oligoFrequencies_2=oligonucleotideFrequency(genomeBin[[i]][j:(j+windowSize-1)],width=2,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]][j:(j+windowSize-1)])),width=2,with.labels=TRUE)
			oligoFrequencies_3=oligonucleotideFrequency(genomeBin[[i]][j:(j+windowSize-1)],width=3,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]][j:(j+windowSize-1)])),width=3,with.labels=TRUE)
			oligoFrequencies_4=oligonucleotideFrequency(genomeBin[[i]][j:(j+windowSize-1)],width=4,with.labels=TRUE)+oligonucleotideFrequency(rev(complement(genomeBin[[i]][j:(j+windowSize-1)])),width=4,with.labels=TRUE)
			oligoFreqCorMatrix<-rbind(oligoFreqCorMatrix,c(as.numeric(names(genomeBin)[i]),j,j+windowSize-1,length(genomeBin[[i]]),runningLength,runningLength+windowSize,cor(log10(baseFrequencies_1+1),log10(oligoFrequencies_1+1)),cor(log10(baseFrequencies_2+1),log10(oligoFrequencies_2+1)),cor(log10(baseFrequencies_3+1),log10(oligoFrequencies_3+1)),cor(log10(baseFrequencies_4+1),log10(oligoFrequencies_4+1))))	
			runningLength=runningLength+length(genomeBin[[i]][j:(j+step-1)])
		}
	}
}
colnames(oligoFreqCorMatrix)<-c("scaffold","scaffoldStart","scaffoldEnd","scaffoldLength","plotPosition_begin","plotPosition_end","cor_GC","cor_di","cor_tri","cor_tetra")

pValues<-1-pnorm(log(1-oligoFreqCorMatrix[,10]),mean=mean(log(1-oligoFreqCorMatrix[,10])),sd=sd(log(1-oligoFreqCorMatrix[,10])))
pCutoff<-sort(pValues)[max(which(sort(pValues)-c(1:length(pValues))*0.05/length(pValues)<0))+1]
significantSlices<-which(pValues<pCutoff)
blockMembership<-cutree(hclust(dist(which(pValues<pCutoff)),method="single"),h=1)
oligoFreqCorMatrix<-cbind(oligoFreqCorMatrix,pValues)

df_tet_n_gracillis <- as.data.frame(oligoFreqCorMatrix)
df_tet_n_gracillis$x_axis <- apply(oligoFreqCorMatrix[,5:6],1,mean)
df_tet_n_gracillis$y_axis <- oligoFreqCorMatrix[,10]
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
df_gracillis_headers <- read.csv("~/master/anna/dataflow/02-headers/n_gracillis_rename.fna.csv")

df_gracillis_headers <- df_gracillis_headers %>%
  separate(X0, into = c("rm", "start", "stop", "strand"), sep = " # ") 

df_gracillis_headers$stop <- as.numeric(df_gracillis_headers$stop)
df_gracillis_headers$start <- as.numeric(df_gracillis_headers$start)

df_gracillis_headers <- df_gracillis_headers %>%
  mutate(orf_add = start + stop) %>%
  mutate(orf_center = round(orf_add / 2), 1) %>%
  select(X, orf_center) 

colnames(df_gracillis_headers)[1] <- "qseqid"

df_gracillis_headers$qseqid <- gsub("n_", "", df_gracillis_headers$qseqid)

df_gracillis_headers <- df_gracillis_headers[startsWith(df_gracillis_headers$qseqid, "gracillis_1"), ]

df_gracillis_AvA <- inner_join(df_plot_gracillis, df_gracillis_headers) %>%
  select(orf_center, mean_pi, genome2) 

colnames(df_gracillis_AvA)[1] <- "x_axis"



df_tet_n_gracillis <- df_tet_n_gracillis %>%
  filter(scaffoldLength == 3072611) %>%
  select(x_axis, y_axis)

df_combined_gracillis <- bind_rows(df_tet_n_gracillis, df_gracillis_AvA)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=20, fig.height=5}
library(cowplot)

p1 <- ggplot(df_combined_gracillis, aes(x_axis)) +
  geom_point(aes(y = mean_pi, colour = genome2), stat = "identity", size = 2) +
  scale_y_continuous(
    expand = expand_scale(mult = c(0, 0.05))
  ) +
  theme_minimal_hgrid(11, rel_small = 1) +
  theme(
    panel.grid.major = element_line(color = "black"),
    axis.line.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks = element_blank(),
    axis.ticks.length = grid::unit(0, "pt"),
    axis.text.y = element_text(color = "black"),
    axis.title.y = element_text(color = "black")
  ) + theme(legend.position = "none") +
  ggtitle("N. gracillis")



p2 <- ggplot(df_combined_gracillis, aes(x_axis, y_axis)) + 
  geom_line(data = df_combined_gracillis[!is.na(df_combined_gracillis$y_axis), ], size = 0.5, color = "grey43") + 
  scale_y_continuous(limits = c(0, 1), position = "right") +
  theme_half_open(11, rel_small = 1) +
  theme(
    axis.ticks.y = element_line(color = "grey43"),
    axis.text.y = element_text(color = "grey43"),
    axis.title.y = element_text(color = "grey43"),
    axis.line.y = element_line(color = "grey43")
  )



aligned_plots <- align_plots(p1, p2,align="hv", axis="tblr")

ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])


```
