---
title: "Untitled"
author: "Cameron Strachan"
date: '2019-09-13'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(scales)
library(ggthemes)
library(RColorBrewer)
```

```{r}
df_taxa <- read.csv("~/master/epithelial/dataflow/00-meta/neubauer2018_wetzels201_99_rdp.csv")
df_taxa <- df_taxa[,-1]
```

```{r}
df_meta <- read.csv("~/master/epithelial/dataflow/00-meta/sample_mapping.csv")
df_meta[] <- lapply(df_meta, as.character)
```

```{r}
counts <- read.delim("~/master/epithelial/dataflow/03-asv-table/neubauer2018_wetzels2017_99.txt", header=FALSE)
counts <- counts[-1,]
counts[] <- lapply(counts, as.character)
names(counts) <- counts[1,]
counts <- counts[-1,]
counts[,2:57] <- lapply(counts[,2:57], as.numeric)
names(counts)[1] <- "asv"

df_counts <- gather(counts, ID, count, -asv) %>%
  inner_join(df_meta) %>% 
  group_by(ID) %>%
  mutate(reads= sum(count)) %>%
  ungroup() %>%
  mutate(counts_normalized = (count / reads)*100)
```

```{r}
df_differential <- df_counts %>%
  filter(Study == 'Neubauer2018') %>%
  group_by(asv, Type) %>%
  mutate(mean_counts_normalized  = mean(counts_normalized)) %>%
  ungroup() %>%
  select(asv, Type, mean_counts_normalized) %>%
  distinct() %>%
  spread(Type, mean_counts_normalized) %>%
  mutate(fold_change = epithelial / digesta) %>%
  mutate(fold_change_cat = if_else(is.nan(fold_change), 0,
                           if_else(fold_change == Inf, 500, fold_change))) %>%
  select(asv, fold_change_cat)
```

```{r}
df_metrics <- df_counts %>%
  inner_join(df_differential) %>%
  inner_join(df_taxa) %>%
  filter(Type == 'epithelial') %>%
  mutate(detected = if_else(count > 0, 1, 0)) %>%
  group_by(asv) %>%
  mutate(per_samples_detected = sum(detected) / 48) %>%
  mutate(mean_counts_normalized = mean(counts_normalized)) %>%
  ungroup() %>%
  mutate(mean_counts_normalized = round(mean_counts_normalized, 2)) 
```

Phylum distributions before and after cut offs for differential abundance (fold change).

```{r}
df_phylum_before <- df_metrics %>%
  select(mean_counts_normalized, phylum) %>%
  distinct() %>%
  group_by(phylum) %>%
  mutate(mean_counts_normalized_phylum_sum = sum(mean_counts_normalized)) %>%
  ungroup() %>%
  select(-mean_counts_normalized) %>%
  distinct() %>%
  filter(mean_counts_normalized_phylum_sum != 0.00) 

df_phylum_after <- df_metrics %>%
  filter(fold_change_cat > 10) %>%
  filter(per_samples_detected > 0.5) %>%
  select(mean_counts_normalized, phylum) %>%
  distinct() %>%
  group_by(phylum) %>%
  mutate(mean_counts_normalized_phylum_sum = sum(mean_counts_normalized)) %>%
  ungroup() %>%
  select(-mean_counts_normalized) %>%
  distinct() %>%
  filter(mean_counts_normalized_phylum_sum != 0.00)
```

```{r}
myColors <- colorRampPalette(brewer.pal(8, "Set2"))(20)
names(myColors) <- levels(df_metrics$phylum)
colScale <- scale_fill_manual(name = "phylum",values = myColors)

plot_phylum_before <- ggplot(df_phylum_before, aes(x="", y=mean_counts_normalized_phylum_sum, fill=phylum))+
geom_bar(width = 1, stat = "identity") 

plot_phylum_before <- plot_phylum_before + coord_polar("y", start=0)

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

plot_phylum_before  + blank_theme +
  theme(axis.text.x=element_blank()) + 
  colScale 
```

```{r}
plot_phylum_after <- ggplot(df_phylum_after, aes(x="", y=mean_counts_normalized_phylum_sum, fill=phylum))+
geom_bar(width = 1, stat = "identity")

plot_phylum_after <- plot_phylum_after + coord_polar("y", start=0)

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

plot_phylum_after  + blank_theme +
  theme(axis.text.x=element_blank()) + 
  colScale 
```

```{r}
df_metrics_after <- df_metrics %>%
  select(asv, phylum, class, order, family, genus, mean_counts_normalized, fold_change_cat, per_samples_detected) %>%
  filter(fold_change_cat > 10) %>%
  filter(per_samples_detected > 0.5) %>%
  distinct()
```


```{r}
qplot(df_metrics_after $phylum, df_metrics_after$mean_counts_normalized) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
