---
title: "Alpha diversity"
author: "Cameron Strachan"
date: '2019-03-14'
output:
  pdf_document: default
  html_document: default
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library("ggpubr")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
shannon <- read.delim("~/master/wolffaeces/dataflow/04-exported-tables/alpha_diversity/shannon.tsv", comment.char="#")
colnames(shannon)[40] <- 'index'
shannon$index_type <- 'shannon'

chao1 <- read.delim("~/master/wolffaeces/dataflow/04-exported-tables/alpha_diversity/chao1.tsv", comment.char="#")
colnames(chao1)[40] <- 'index'
chao1$index_type <- 'chao1'

df_div <- bind_rows(shannon, chao1) %>%
  separate(SAMPLEtype, into = c("species", "sample"), remove = FALSE, sep = "_") %>%
  filter(species != "C") %>%
  filter(sample == "F")

df_div$Contact_to_WSC_animals <- as.character(df_div$Contact_to_WSC_animals)
df_div$Contact_to_WSC_animals[is.na(df_div$Contact_to_WSC_animals)] <- "not_relevant"
df_div$Contact_to_WSC_animals <- as.factor(df_div$Contact_to_WSC_animals)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=4, fig.height=6}
df_div_1 <- df_div %>%
  filter(index_type == 'shannon' | index_type == 'chao1')

p <- ggboxplot(df_div_1, x = "species", y = "index",
                color = "species", palette =c("#c65999", "#7aa456", "#777acd", "#c96d44"), add = "jitter",  facet.by = "index_type") +
  facet_grid(index_type ~ ., scales = "free_y")
p
```



