---
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(printr)
library(ggplot2)
library(cowplot)
library(printr)
library(reshape2)
library(knitr)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
meta <- read.csv("~/master/mycotoxins/dataflow/00-meta/wetzels2018_fastq.csv")
df <- read.delim("~/master/mycotoxins/dataflow/03-asv-table/wetzels2017.txt", skip = 1, header = TRUE)
colnames(df)[1] <- 'asv_id'

col_to_gather <- names(df)[!startsWith(names(df), "ERX")]
df <- melt(df, id = col_to_gather)
colnames(df)[2:3] <- c('sra_accession', 'count')

df$asv_id <- as.character(df$asv_id)
meta$day <- as.character(meta$day)
meta$treatment <- as.character(meta$treatment)

df_merge <- inner_join(df, meta) %>% 
  group_by(asv_id, day, treatment) %>%
  mutate(med_count = median(count)) %>%
  mutate(sd_count = sd(count)) %>%
  mutate(cv_count =  (sd(count) / mean(count))*100) %>%
  mutate(n_count = length(count)) %>%
  ungroup()


df_ttest <- df_merge %>%
  select(-sample_id, -sra_accession) %>%
  
  group_by_at(vars(-count)) %>%
  summarize(count = list(unique(count))) %>%
  ungroup() %>%
  select(asv_id, day, count, treatment)


treatment_df <- df_ttest %>%
  filter(treatment == 'infected') %>%
  select(-treatment) %>%
  rename(count_treatment = count)

control_df <- df_ttest %>%
  filter(treatment == 'non-infected') %>%
  select(-treatment) %>%
  rename(count_control = count)

df_ttest <- inner_join(control_df, treatment_df) %>%
  rowwise() %>%
  mutate(ncontrol = length(unlist(count_control))) %>%
  mutate(ntreatment = length(unlist(count_treatment))) %>%
  filter(ncontrol == 3) %>%
  filter(ntreatment == 3) %>%
  mutate(pvalue = t.test(count_treatment, count_control, paired = FALSE)$p.value) %>%
  ungroup() %>%
  filter(pvalue < 0.1)

df_merge <- df_merge %>%
  select(asv_id, day, treatment, med_count, sd_count) %>%
  
  distinct() %>%
  


  group_by(asv_id) %>%
  mutate(data_points = length(unique((med_count)))) %>%
  ungroup() %>%
  
  filter(data_points > 3)


df_merge$asv_id <- as.character(df_merge$asv_id)

selected_seqs <- unique(df_merge$asv_id)[unique(df_merge$asv_id) %in% unique(df_ttest$asv_id)]

df_plot <- df_merge[df_merge$asv_id %in% selected_seqs,]
df_plot$day <- as.numeric(df_plot$day)

selected_seqs
```
The two most abundant OTUs (7.5% and 5.9% relative abundance) were classified as Prevotella bryantii and Prevotella ruminicola with 100% sequence similarity compared to the best Greengenes type strain hit.

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}
plot <- ggplot(df_plot, aes(x=day)) +
    theme_few() +
    geom_errorbar(aes(ymin = med_count -
                      sd_count, ymax =  med_count +
                      sd_count), width = 0.05, size = 0.25) +
    geom_point(aes(y = med_count, colour = treatment, shape = treatment),
      stat = "identity", fill = "lightgrey", size = 5) +
    theme(strip.text = element_text(size = 6),
      plot.title = element_text(size = 25), axis.text.x = element_text(angle = 90, hjust = 1, size = 20),  axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20)) + facet_grid(. ~ asv_id)

plot
```
