---
title: "Untitled"
author: "Cameron Strachan"
date: '2020-04-29'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
df <- read_csv("~/master/scratch/output/ani_output.csv")
```

```{r}
df <- df %>%
  mutate(fragment_snp = 1000 - ((round(fragment_ani, 1) / 100) * fragment_size1)) %>%
  mutate(genome_wide_snp = 1000 - ((round(genome_wide_ani, 1) / 100) * fragment_size1)) %>%
  mutate(snp_diff = fragment_snp - genome_wide_snp)
```

```{r}
meta <- read.csv("~/master/scratch/meta.csv", colClasses = "character")

meta1 <- meta %>% select(file, host)
meta1$host1 <- meta1$host
meta1$host <- NULL
meta1$genome1 <- gsub(".fna", "", meta1$file)
meta1$file <- NULL

meta2 <- meta1
colnames(meta2) <- c('host2', 'genome2')
```

```{r}
df_pos <- read_csv("~/master/scratch/output/fragment_map.csv")
colnames(df_pos)[4] <- "fragment1"

df_pos <- df_pos %>%
  mutate(position = (start + stop) /2)
```

```{r}
df_plot <- df  %>%
  inner_join(meta1) %>%
  inner_join(meta2) %>%
  inner_join(df_pos) %>%
  filter(host1 == "cattle") %>%
  arrange(genome2) %>%
  arrange(host2)

df_plot$genome2 <- factor(df_plot$genome2, levels = as.character(unique(df_plot$genome2)))
```

```{r, fig.height=12, fig.width=7}
ggplot(df_plot, aes(x=position, y=snp_diff, colour=host2)) +
  geom_line(size=0.5, alpha=0.9, linetype=2) + 
  facet_grid(genome2 ~ .)
```