---
title: "Untitled"
author: "Cameron Strachan"
date: '2020-04-29'
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
df <- read_csv("~/master/scratch/output/conserved_regions_output.csv")
```

```{r}
meta <- read.csv("~/master/scratch/meta.csv", colClasses = "character")

meta1 <- meta %>% select(file, host)
meta1$host1 <- meta1$host
meta1$host <- NULL
meta1$genome1 <- gsub(".fna", "", meta1$file)
meta1$file <- NULL

meta2 <- meta1
colnames(meta2) <- c('host2', 'genome2')
```

```{r}
df_pos <- read_csv("~/master/scratch/output/fragment_map.csv")
colnames(df_pos)[4] <- "fragment1"

df_pos <- df_pos %>%
  mutate(position = (start + stop) / 2)
```

```{r}
df_trim <- df %>%
  filter(n_continuous_frags >= 10) 
```

```{r}
df_plot <- df_trim  %>%
  inner_join(meta1) %>%
  inner_join(meta2) %>%
  filter(genome1 != "GCF_010232325.1_ASM1023232v1_major_contig") %>%
  filter(genome1 != "GCF_002407145.1_ASM240714v1_major_contig") %>%
  filter(genome1 != "GCF_001305715.1_ASM130571v1_major_contig") %>%
  
  filter(genome2 != "GCF_010232325.1_ASM1023232v1_major_contig") %>%
  filter(genome2 != "GCF_002407145.1_ASM240714v1_major_contig") %>%
  filter(genome2 != "GCF_001305715.1_ASM130571v1_major_contig")
  
df_plot$host2 <- factor(df_plot$host2, levels = c("chicken", "human", "cattle"))
```

```{r, fig.height=8, fig.width=8}
p1 <- ggplot(df_plot, aes(x = fragment1, y = snp_diff, colour = host2)) +
  geom_point(size = 0.5) +
  facet_wrap(host1 ~ genome1) +
  theme_minimal()

p1
```


