---
title: "Untitled"
author: "Cameron Strachan"
date: '2020-04-29'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(scales)
library(cowplot)
library(viridis)
```

```{r}
df_regions <- read_csv("~/master/scratch/output/conserved_regions_output.csv")
df_ani <- read_csv("~/master/scratch/output/ani_output.csv")
```

```{r}
meta <- read.csv("~/master/scratch/meta.csv", colClasses = "character")

meta2 <- meta %>% select(file, host)
meta2$host2 <- meta2$host
meta2$host <- NULL
meta2$genome2 <- gsub(".fna", "", meta2$file)
meta2$file <- NULL
```

```{r}
df_ani <- df_ani %>%
  select(genome1, genome2, genome_wide_ani) %>%
  distinct()

df_ani_spread <- df_ani %>%
  spread(genome2, genome_wide_ani)

df_ani_matrix <- as.matrix(df_ani_spread[,2:ncol(df_ani_spread)])  
row.names(df_ani_matrix) <- df_ani_spread$genome1

ani_distance <- dist(df_ani_matrix) # method="man" # is a bit better
ani_hclust <- hclust(ani_distance, method = "complete")
ord_ani <- ani_hclust$order
```

```{r}
df_distance <- df_regions %>%
  filter(snp_diff != 0) %>%
  group_by(genome1, genome2, snp_diff) %>%
  mutate(n_frags = length(unique(fragment1))) %>%
  ungroup() %>% 
  
  mutate(distance = (1 / (n_frags / snp_diff)*100)) %>%
  
  select(genome1, genome2, n_frags, snp_diff, distance) %>%
  distinct() %>%
  
  group_by(genome1, genome2) %>%
  top_n(1, (1/distance)) %>%
  ungroup() %>%
  
  select(genome1, genome2, distance) %>%
  
  distinct() 

df_distance_spread <- df_distance %>%
  spread(genome2, distance)

df_distance_spread[is.na(df_distance_spread)] <- 0

df_distance_matrix <- as.matrix(df_distance_spread[,2:ncol(df_distance_spread)])  
row.names(df_distance_matrix) <- df_distance_spread$genome1

distance <- dist(df_distance_matrix) # method="man" # is a bit better
hclust <- hclust(distance, method = "complete")
ord_distance <- rev(hclust$order)
```

```{r}
df_ani <- df_ani %>%
  inner_join(meta2)

df_distance <- df_distance %>%
  inner_join(meta2)

df_add_distance <- df_ani %>%
  filter(genome1 == genome2) %>%
  select(-genome_wide_ani)

df_add_distance$distance <- 0

df_distance <- bind_rows(df_distance, df_add_distance)
```

```{r, fig.height=4, fig.width=8}
df_distance$genome1 <- factor(df_distance$genome1, levels = rownames(df_distance_matrix)[ord_distance])
df_distance$genome2 <- factor(df_distance$genome2, levels = colnames(df_distance_matrix)[ord_distance])
df_distance$x_holder <- "X"

heatmap_distance <- ggplot(df_distance, aes(genome1, genome2) ) +
  geom_tile(aes(fill = distance)) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) +
  scale_fill_viridis(direction = 1)  + 
  theme(legend.title = element_blank()) + 
  theme(legend.position = "none") 

heatmap_host_distance <- ggplot(df_distance, aes(x_holder, genome2) ) +
  geom_tile(aes(fill = host2)) +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) + 
  scale_fill_viridis(discrete = TRUE, option = "D") + 
  theme(legend.title = element_blank())

plot_grid(heatmap_distance, heatmap_host_distance, rel_widths = c(4,1))
```

```{r, fig.height=4, fig.width=8}
df_ani$genome1 <- factor(df_ani$genome1, levels = rownames(df_ani_matrix)[ord_distance])
df_ani$genome2 <- factor(df_ani$genome2, levels = colnames(df_ani_matrix)[ord_distance])
df_ani$x_holder <- "X"

heatmap_ani <- ggplot(df_ani, aes(genome1, genome2) ) +
  geom_tile(aes(fill = genome_wide_ani)) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) +
  scale_fill_viridis(direction = -1) + 
  theme(legend.title = element_blank()) + 
  theme(legend.position = "none") 

heatmap_host_ani <- ggplot(df_ani, aes(x_holder, genome2) ) +
  geom_tile(aes(fill = host2)) +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) + 
  scale_fill_viridis(discrete = TRUE, option = "D") + 
  theme(legend.title = element_blank())

plot_grid(heatmap_ani, heatmap_host_ani, rel_widths = c(4,1))
```