---
title: "Untitled"
author: "Cameron Strachan"
date: '2019-01-07'
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggthemes)
library(stringi)
library(ggplot2)
library(ggdendro)
library(reshape2)
library(grid)
library(ape)
library(adephylo)
library(stringr)
library(distory)
library(gridExtra)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.height=5}
df_distance <- read.csv("~/master/rumen/dataflow/04-analysis-tables/rumen_prevotella_checkMtree_distance.csv") 

df_distance$X <- gsub("_rename", "", df_distance$X)
df_distance$X <- gsub("submission.assembly", "", df_distance$X)
df_distance$X <- gsub("final.assembly", "", df_distance$X)
df_distance$X <- gsub("-", "", df_distance$X)
df_distance$X <- gsub("_IMGtaxon_2693429877_annotated_assembly", "", df_distance$X)
df_distance$X <- gsub("_genomic", "", df_distance$X)
df_distance$X <- gsub("\\.", "", df_distance$X)

df_distance[is.na(df_distance)] <- 100

df_distance_scaled <- df_distance
df_distance[,2:43] <- scale(df_distance[,2:43])

df_distance.matrix <- as.matrix(df_distance[, -c(1)])
rownames(df_distance.matrix) <- df_distance$X
df_distance.matrix.dendro <- as.dendrogram(hclust(d = dist(x = df_distance.matrix)))

dendro.plot <- ggdendrogram(data = df_distance.matrix.dendro, rotate = FALSE) +
  theme(
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 5),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank()) 
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
df_pi <- read.csv("~/master/rumen/dataflow/04-analysis-tables/selected_genomes_sharedPI.csv")
df_pi$X <- NULL


df_pi$file1 <- gsub("_IMGtaxon_2693429877_annotated_assembly", "", df_pi$file1)
df_pi$file2 <- gsub("_IMGtaxon_2693429877_annotated_assembly", "", df_pi$file2)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
df_pi_shared_spread <- df_pi %>%
  spread(file2, mean_mean_pi)

df_pi_shared_spread[is.na(df_pi_shared_spread)] <- 100
 
df_pi_shared_spread_scaled <- df_pi_shared_spread
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.height=7.5, fig.width=6}
df_pi <- melt(df_pi_shared_spread_scaled, by = c("mean_mean_pi"))
colnames(df_pi) <- c("file1", "file2", "mean_mean_pi")

order <- order.dendrogram(df_distance.matrix.dendro)

df_pi$file1 <- factor(df_pi$file1,
                               levels = df_distance_scaled$X[rev(order)], 
                               ordered = TRUE)

df_pi$file2 <- factor(df_pi$file2,
                               levels = df_distance_scaled$X[order], 
                               ordered = TRUE)

heatmap.plot <- ggplot(data = df_pi, aes(x = file2, y = file1)) +
  geom_tile(aes(fill = mean_mean_pi)) +
      theme(axis.text.x = element_blank(),  
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank()) +
  scale_fill_gradient2() 


tmp <- ggplot_gtable(ggplot_build(heatmap.plot))
leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
legend <- tmp$grobs[[leg]]

heatmap.plot <- heatmap.plot +
  theme(legend.position = "none")

#heatmap.plot
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.height=7.5, fig.width=6}
df_counts <- read.delim("~/master/rumen/rumen_prevotella.txt", header=FALSE) %>%
  filter(V3 != 0) %>%
  filter(V1 != "__not_aligned") %>%
  filter(V1 != "__too_low_aQual") %>%
  filter(V1 != "__no_feature") %>%
  filter(V1 != "__ambiguous") %>%
  select(-V2)

colnames(df_counts) <- c("ID", "count")

df_counts$ID <- as.character(df_counts$ID)

df_gff3 <- read.delim("~/master/rumen/dataflow/01-prot/genes/rumen_prevotella.gff3", header=FALSE, comment.char="#") %>%
  separate(V9, c("ID"), sep = ";") %>%
  select(-V2, -V3, -V6, -V8)

df_gff3$ID <- gsub("ID=", "", df_gff3$ID)

colnames(df_gff3)[1:4] <- c("contig", "start", "end", "direction")

df <- inner_join(df_counts, df_gff3) %>%
  rowwise() %>%
  mutate(genome = stri_reverse(stri_split_fixed(stri_reverse(contig),"_",n = 2)[[1]][2]))

df_genome <- df %>%
  group_by(genome) %>%
  mutate(total_counts = sum(count)) %>%
  ungroup() %>%
  select(genome, total_counts) %>%
  distinct()

df_genome$genome <- gsub("_rename", "", df_genome$genome)
df_genome$genome <- gsub("submission.assembly", "", df_genome$genome)
df_genome$genome <- gsub("final.assembly", "", df_genome$genome)
df_genome$genome <- gsub("-", "", df_genome$genome)
df_genome$genome <- gsub("_IMGtaxon_2693429877_annotated_assembly", "", df_genome$genome)
df_genome$genome <- gsub("_genomic", "", df_genome$genome)
df_genome$genome <- gsub("\\.", "", df_genome$genome)

df_genome$genome <- factor(df_genome$genome,
                               levels = df_distance_scaled$X[rev(order)], 
                               ordered = TRUE)

bp.y <- ggplot(data = df_genome, aes(x = genome, y = total_counts)) + 
    geom_bar(stat = "identity", aes(fill = total_counts)) + coord_flip() + theme_gray() +
    theme(axis.title.x = element_blank(), axis.text.x = element_blank(),
          axis.ticks.x = element_blank(), axis.text.y = element_text(size = 12), 
          axis.title.y = element_blank(),
          legend.position="none") +
    scale_fill_distiller(name = "Value", palette = "Reds", direction = 1) 
```



```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.height=7.5, fig.width=6}

grid.arrange(dendro.plot, legend, heatmap.plot, bp.y, nrow = 2, ncol = 2, 
             widths = c(30, 40), heights = c(40, 60))
```