---
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(printr)
library(ggplot2)
library(cowplot)
library(printr)
library(reshape2)
library(knitr)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_meta <- read.csv("~/master/rumen/dataflow/00-meta/wetzels2018_fastq.csv")

df_100 <- read.delim("~/master/rumen/dataflow/03-asv-table/wetzels2017-100.txt", skip = 1, header = TRUE)
df_100$clustering <- 100

df_99 <- read.delim("~/master/rumen/dataflow/03-asv-table/wetzels2017-99.txt", skip = 1, header = TRUE)
df_99$clustering <- 99

df_97 <- read.delim("~/master/rumen/dataflow/03-asv-table/wetzels2017-97.txt", skip = 1, header = TRUE)
df_97$clustering <- 97

df <- bind_rows(df_100, df_99, df_97)

colnames(df)[1] <- 'asv_id'

col_to_gather <- names(df)[!startsWith(names(df), "ERX")]
df <- melt(df, id = col_to_gather)
colnames(df)[3:4] <- c('sra_accession', 'count')

df$asv_id <- as.character(df$asv_id)
df_meta$day <- as.character(df_meta$day)
df_meta$treatment <- as.character(df_meta$treatment)

df_complete <- inner_join(df, df_meta)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_metrics <- df_complete %>% 
  
  filter(count > 0) %>%
  group_by(asv_id, clustering, day, treatment) %>%
  mutate(med_count = median(count)) %>%
  mutate(sd_count = sd(count)) %>%
  mutate(cv_count =  (sd(count) / mean(count))*100) %>%
  mutate(n_count = length(count)) %>%
  ungroup() %>%
  filter(n_count == 3)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_count_summary <- df_metrics %>%
  select(-sample_id, -sra_accession) %>%
  
  group_by_at(vars(-count)) %>%
  summarize(count = list(unique(count))) %>%
  ungroup() %>%
  select(asv_id, clustering, day, count, treatment) %>%
  
  rowwise() %>%
  mutate(n = as.numeric(length(unlist(count)))) 

df_control <- df_count_summary %>%
  filter(treatment == 'non-infected') %>%
  select(-treatment) %>%
  rename(count_control = count)

df_treatment <- df_count_summary %>%
  filter(treatment == 'infected') %>%
  select(-treatment) %>%
  rename(count_treatment = count)

df_ttest <- inner_join(df_control, df_treatment) %>%
  rowwise() %>%
  mutate(ncontrol = length(unlist(count_control))) %>%
  mutate(ntreatment = length(unlist(count_treatment))) %>%
  filter(ncontrol == 3) %>%
  filter(ntreatment == 3) %>%
  mutate(pvalue = t.test(count_treatment, count_control, paired = FALSE)$p.value) %>%
  ungroup() %>%
  filter(pvalue < 0.1)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_plot <- df_ttest %>%
  select(asv_id, clustering) %>% 
  distinct() %>%
  inner_join(df_metrics)

df_plot$day <- as.numeric(df_plot$day)
```
The two most abundant OTUs (7.5% and 5.9% relative abundance) were classified as Prevotella bryantii and Prevotella ruminicola with 100% sequence similarity compared to the best Greengenes type strain hit.

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}
plot <- ggplot(df_plot, aes(x=day)) +
    theme_few() +
    geom_errorbar(aes(ymin = med_count -
                      sd_count, ymax =  med_count +
                      sd_count), width = 0.05, size = 0.25) +
    geom_point(aes(y = med_count, colour = treatment, shape = treatment),
      stat = "identity", fill = "lightgrey", size = 5) +
    theme(strip.text = element_text(size = 8),
      plot.title = element_text(size = 25), axis.text.x = element_text(angle = 90, hjust = 1, size = 20),  axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20)) + facet_grid(clustering ~ asv_id)

plot
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_ignore_treatment <- df_metrics %>%
  select(-treatment, -sra_accession, -sample_id) %>%
  group_by(asv_id, clustering, day) %>%
  mutate(med_count = median(count)) %>%
  mutate(sd_count = sd(count)) %>%
  mutate(cv_count =  (sd(count) / mean(count))*100) %>%
  ungroup() %>%

  group_by(asv_id, clustering) %>%
  mutate(n_days = length(unique(day))) %>%
  ungroup() %>%
  
  filter(n_days > 2)


df_ignore_treatment $day <- as.numeric(df_ignore_treatment $day)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
datalist_plots_gfp = list()
i <- 1

for (seq in unique(df_ignore_treatment$asv_id)){
  df_plot <- df_ignore_treatment %>%
    filter(asv_id == seq)
  
  plot <- ggplot(df_plot, aes(x=day)) +
    theme_few() +
    geom_errorbar(aes(ymin = med_count -
                      sd_count, ymax =  med_count +
                      sd_count), width = 0.05, size = 0.25) +
    geom_point(aes(y = med_count),
      stat = "identity", fill = "lightgrey", size = 5) +
    theme(strip.text = element_text(size = 8),
      plot.title = element_text(size = 25), axis.text.x = element_text(angle = 90, hjust = 1, size = 20),  axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20)) + facet_grid(clustering ~ .)
  
  datalist_plots_gfp[[i]] <- plot_grid(plot, ncol = 1)
  i <- i + 1
}
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.height=5, fig.width=10}
for (i in 1:length(datalist_plots_gfp)) {
  plot(datalist_plots_gfp[[i]])
  cat("\r\n\r\n")
}
```