---
title: "Untitled"
author: "Cameron Strachan"
date: '2020-04-07'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
df_dada2 <- read.csv("~/master/rusitec/dataflow/00-meta/dada2_stats.csv")
df_dada2$sample <- as.character(df_dada2$sample)

df_vbc_map <- read.csv("~/master/rusitec/dataflow/00-meta/vbc_sample_map.csv")
df_vbc_map$run <- as.character(df_vbc_map$run)
df_vbc_map$reactor <- as.character(df_vbc_map$reactor)
df_vbc_map$sample <- as.character(df_vbc_map$sample)
df_vbc_map$time <- as.character(df_vbc_map$time)

df_tp <- read.csv("~/master/rusitec/dataflow/00-meta/meta_TP.csv")
df_tp$time <- as.character(df_tp$time)

df_t48 <- read.csv("~/master/rusitec/dataflow/00-meta/meta_T48.csv")
df_t48$run <- '48'

df_t49 <- read.csv("~/master/rusitec/dataflow/00-meta/meta_T49.csv")
df_t49$run <- '49'

df_runs <- rbind(df_t48, df_t49)
df_runs$run <- as.character(df_runs$run)
df_runs$reactor <- as.character(df_runs$reactor)
df_runs$reactor <- as.character(df_runs$reactor)

df_meta <- inner_join(df_dada2, df_vbc_map) %>%
  left_join(df_tp) %>%
  left_join(df_runs) %>%
  filter(treatment != "NC") %>%
  filter(time != "0") %>%
  filter(time != "288")

df_meta$sample <- paste("X", df_meta$sample, sep = "")

row.names(df_meta) <- df_meta[,1]
df_meta$treatment <- as.character(df_meta$treatment)
selected_samples <- row.names(df_meta)
```

```{r}
library("phyloseq")
library("ape")
library(plyr)
library(tsnemicrobiota)
library(cowplot)
```

```{r}
files <- c("forward-feature-table.txt", "forward-feature-table-99.txt", "forward-feature-table-98.txt", "forward-feature-table-97.txt", "forward-feature-table-96.txt", "forward-feature-table-95.txt")

otu_table_list <- list()
i <- 1


for (file in files){
  input_table <- paste("~/master/rusitec/dataflow/03-asv-table/", file, sep = "")
  df_counts <- read.csv(input_table, sep = '\t', skip = 1)
  df_counts <- cbind(df_counts[,1], df_counts[,names(df_counts) %in% selected_samples])
  colnames(df_counts)[1] <- "asv_id"
  df_counts <- df_counts[order(df_counts$asv_id),] 
  numsamples <- length(df_counts)
  otumat <- as.matrix(df_counts[,2:numsamples])
  rownames(otumat) <- as.data.frame(df_counts)[,1]
  otu_table_list[[i]] <- otumat
  i <- i + 1
}
```


  
```{r}
clustering <- 100
i <- 1
plots_list <- list()

for (j in 1:6){
  OTU = otu_table(otu_table_list[[j]], taxa_are_rows = TRUE)
  
  samplesdata <- sample_data(df_meta)
  physeq = phyloseq(OTU, samplesdata)
  
  physeq_trim = filter_taxa(physeq, function(x) sum(x > 3) > 3, TRUE)
  #physeq_norm = transform_sample_counts(physeq_trim, function(x) sqrt(x))
  physeq_norm = transform_sample_counts(physeq_trim, function(x) x / sum(x))
  
  t_SNE <- tsne_phyloseq(physeq_norm, distance = "bray", perplexity = 25, 
                         precomputed_distance = NULL, pseudocounts = 1, verbose = 1,
                         rng_seed = NULL, philr_options = list(), control = list())
  
  plot_header = paste("TSNE (bray) at", as.character(clustering), sep = " ")
  
  set.seed(3)
  
  tsne_plot <- plot_tsne_phyloseq(physeq_norm, t_SNE,
                                  color = 'treatment', title=plot_header,shape="time") +
    geom_point(size=1.5) +
    theme_classic()
  
  plots_list[[i]] <- tsne_plot
  
  clustering <- clustering - 1
  i <- i + 1
}
```

```{r, fig.width=11, fig.height=11}
plot_grid(plotlist=plots_list)
```
