---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
df_compiled <- read.csv("~/master/rusitec/dataflow/04-exported-tables/df_forward_compiled.csv")
df_compiled$X <- NULL
```

```{r}
df_compiled <- df_compiled %>%
  filter(counts > 0) %>%
  mutate(rel_abundance = (counts / non.chimeric)*100) %>%
  filter(reactor != 'NC') %>%
  filter(time != "0") %>%
  filter(!(time == "288" & run == "48")) %>%
  
  group_by(run, time, day, treatment) %>%
  mutate(n = length(unique(sample))) %>%
  ungroup() %>%
  
  filter(n > 2) %>%
  
  group_by(sample) %>%
  mutate(total_reads = sum(counts)) %>%
  ungroup()

df_compiled$family <- as.character(df_compiled$family)  

df_family <- df_compiled %>%
  
  group_by(sample, family) %>%
  mutate(sum_relative_abundance_family = sum(rel_abundance)) %>%
  ungroup() %>%
  
  
  group_by(day, time, run, treatment, family) %>%
  mutate(mean_rel_abundance_family = mean(sum_relative_abundance_family)) %>%
  mutate(sd_rel_abundance_family = sd(sum_relative_abundance_family)) %>%
  ungroup() %>%
  
  group_by(family) %>%
  mutate(sample_family = length(unique((sample)))) %>%
  ungroup() %>%
  
  select(run, time, day, treatment, family, mean_rel_abundance_family, sd_rel_abundance_family, sample_family) %>%
  distinct() %>%
  arrange(desc(mean_rel_abundance_family)) %>%
  filter(!is.na(family)) %>%
  filter(!is.na(sd_rel_abundance_family)) %>%
  filter(sample_family > 20)


df_family$family <- as.character(df_family$family)
fams <- unique(df_family$family)
```

```{r}
plot_list <- list()
i <- 1

for (fam in fams){

df_plot <- df_family %>%
  filter(family == fam)

plot <- ggplot(df_plot, aes(y = mean_rel_abundance_family, x = treatment, fill = treatment)) + geom_bar(stat = "identity", color="black", alpha=0.5,
  position=position_dodge()
)  +
  geom_errorbar(aes(ymin=mean_rel_abundance_family-sd_rel_abundance_family, ymax=mean_rel_abundance_family+sd_rel_abundance_family), width=.2,
                 position=position_dodge(.9)) +
 labs(x="Category" , y= "Percentage (%)")+
  theme_minimal() +
  theme(strip.text = element_text(size = 6),
          plot.title = element_text(size = 16),
          axis.text.x = element_text(angle = 90, hjust = 1, size = 14),
          axis.text.y = element_text(size = 12),
          axis.title.x = element_text(size = 16),
          axis.title.y = element_text(size = 16)) + 
  theme(legend.position = "none") +
  theme(legend.title=element_text(size=14)) +
  ylab("Percentage of Sample") +
  xlab("Individual Sample") +
  facet_grid(run ~ day,  scales = "free_y") +
  ggtitle(fam) 

  plot_list[[i]] <- plot
  i <- i + 1
}
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=6, fig.height=6}
for (i in 1:length(plot_list)) {
  plot(plot_list[[i]])
  cat("\r\n\r\n")
}
```
