---
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
library(cowplot)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_phylocounts_meta <- read.csv("~/master/milk/dataflow/00-meta-merge/sample-complete-all.txt", sep = "\t")

df_phylocounts_meta <- df_phylocounts_meta %>% 
  unite(Time_Injection, c("Time", "Injection"), sep = "-") %>%
  unique()

df_phylocounts_meta <- as.data.frame(df_phylocounts_meta)
row.names(df_phylocounts_meta) <- df_phylocounts_meta[,1]
df_phylocounts_meta[,1] <- NULL
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_phlycounts_counts <- read.csv("~/master/milk/dataflow/03-asv-table-merge/feature-table-97.txt", sep = '\t', skip = 1)
colnames(df_phlycounts_counts)[1] <- "asv_id"

df_phlycounts_counts <- df_phlycounts_counts[order(df_phlycounts_counts$asv_id),] 

numsamples <- length(df_phlycounts_counts)

otumat <- as.matrix(df_phlycounts_counts[,2:numsamples])
rownames(otumat) <- as.data.frame(df_phlycounts_counts)[,1]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_phlycounts_tax  <- read.csv("~/master/milk/dataflow/03-asv-table-merge/taxonomy.tsv", sep = '\t')
df_phlycounts_tax$Confidence <- NULL
colnames(df_phlycounts_tax)[1] <- 'asv_id'
df_phlycounts_tax$Taxon <- gsub("D_.__", "", df_phlycounts_tax$Taxon)

df_phlycounts_tax <- df_phlycounts_tax %>%
  separate(Taxon , into = c("domain", "phylum", "class", "order", "family", "genus", "species"), sep = ";")

df_phlycounts_tax$phylum <- as.character(df_phlycounts_tax$phylum)
df_phlycounts_tax$family <- as.character(df_phlycounts_tax$family)
df_phlycounts_tax$class<- as.character(df_phlycounts_tax$class)
df_phlycounts_tax$order <- as.character(df_phlycounts_tax$order)
df_phlycounts_tax$genus <- as.character(df_phlycounts_tax$genus)
df_phlycounts_tax$species <- as.character(df_phlycounts_tax$species)

df_phlycounts_tax[is.na(df_phlycounts_tax)] <- "NotAssigned"

df_phlycounts_tax <- df_phlycounts_tax[order(df_phlycounts_tax$asv_id),] 

numsamples2 <- length(df_phlycounts_tax)

taxmat <- as.matrix(df_phlycounts_tax[,2:numsamples2])
rownames(taxmat) <- as.data.frame(df_phlycounts_tax)[,1]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library("phyloseq")
library("ape")
#library(plyr)

tree = read.tree("~/master/milk/dataflow/04-tree-merge/tree.nwk")

OTU = otu_table(otumat, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)
samplesdata <- sample_data(df_phylocounts_meta)
physeq = phyloseq(OTU, TAX, samplesdata, tree)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=3, fig.width=7}
library(decontam)

sample_data(physeq)$is.neg <- sample_data(physeq)$SampleOrControl == "Control"
contam.prev05 <- isContaminant(physeq, method="prevalence", neg="is.neg", threshold=0.6)

List_of_contaminants <- subset(contam.prev05,contam.prev05$contaminant == TRUE)
List_of_contaminants$asv_id <- rownames(List_of_contaminants)
taxa <- as.data.frame(taxmat)
taxa$asv_id <- rownames(taxmat)
List_of_contaminants <- merge(List_of_contaminants, taxa, by="asv_id")

physeq.neg <- prune_samples(sample_data(physeq)$SampleOrControl == "Control", physeq)
physeq.neg.presence <- transform_sample_counts(physeq.neg, function(abund) 1*(abund>0))

physeq.pos <- prune_samples(sample_data(physeq)$SampleOrControl == "Sample", physeq)
physeq.pos.presence <- transform_sample_counts(physeq.pos, function(abund) 1*(abund>0))

df.pres <- data.frame(prevalence.pos=taxa_sums(physeq.pos.presence), prevalence.neg=taxa_sums(physeq.neg.presence),
                      contam.prev=contam.prev05)

#ggplot(data=df.pres, aes(x=prevalence.neg, y=prevalence.pos, color=contam.prev.contaminant)) + geom_jitter() + ggtitle("Contamination - TRUE")

over10 <- rownames(subset(df.pres, prevalence.neg > 10))
all_taxa = taxa_names(physeq)
my_contaminants <- c(subset(List_of_contaminants, select = asv_id))
my_contaminants <- unique(unlist(c(my_contaminants, over10)))
my_taxa <- all_taxa[!(all_taxa %in% my_contaminants)]

physeq_no_cont = prune_taxa(my_taxa, physeq)


physeq_no_cont_trim_4000 = prune_samples(sample_sums(physeq_no_cont)>=4000, physeq_no_cont)

physeq_no_cont_trim_rel_4000  = transform_sample_counts(physeq_no_cont_trim_4000, function(x) x / sum(x) )

physeq_no_cont_trim_rel_4000 = filter_taxa(physeq_no_cont_trim_rel_4000, function(x) mean(x) > 0.025, TRUE)

physeq_no_cont_trim_rel_df_4000 <- psmelt(physeq_no_cont_trim_rel_4000)

physeq_no_cont_trim_rel_df_4000 <- physeq_no_cont_trim_rel_df_4000[!(grepl("LK", physeq_no_cont_trim_rel_df_4000$Sample)), ]

physeq_no_cont_trim_rel_df_4000$Read_cutoff <- 4000
```


# Cut-off 4000 reads - Average across cows


```{r, echo=FALSE, message=FALSE, warning=FALSE}
physeq_no_cont_trim_rel_df_mean <- physeq_no_cont_trim_rel_df_4000 %>%
  group_by(Time_Injection, Sara, LPS, family) %>%
  mutate(mean_abundance = mean(Abundance)) %>%
  ungroup() %>%
  select(Time_Injection, Sara, LPS, family, mean_abundance) %>%
  distinct()

physeq_no_cont_trim_rel_df_mean$family <- factor(physeq_no_cont_trim_rel_df_mean$family, levels = c("Staphylococcaceae", "Peptostreptococcaceae", "Dermabacteraceae", "Beijerinckiaceae", "Streptococcaceae", "Erysipelotrichaceae", "Lachnospiraceae"))

colors <- c("#8f48b5", "#90ce55", "#c44d55", "#7db799", "#4b3a3e", "#bc934a", "#9c93c0")
names(colors) <- c("Staphylococcaceae", "Peptostreptococcaceae", "Dermabacteraceae", "Beijerinckiaceae", "Streptococcaceae", "Erysipelotrichaceae", "Lachnospiraceae")


physeq_no_cont_trim_rel_df_mean$Time_Injection <- factor(physeq_no_cont_trim_rel_df_mean$Time_Injection, levels = c("1-Before", "32-Before", "32-After", "34-After"))

bar_plot <- ggplot() + geom_bar(
  aes(y = mean_abundance, x = Time_Injection, fill = family),
  data = physeq_no_cont_trim_rel_df_mean,
  stat = "identity" ,
  position = "dodge"
)  +labs(x="Category" , y= "Percentage (%)")+
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 20),
        #axis.text.x = element_blank(), 
        axis.text.y = element_text(size = 20), 
        strip.text.x = element_text(size = 30),
        strip.text.y = element_text(size = 30),
        axis.title.y = element_text(size = 36),
        axis.title.x = element_text(size = 36)) +
        #axis.title.x = element_blank()) + 
     facet_grid(Sara~LPS, scales = 'free_x')+
  ylab("Mean Percentage of Sample") + 
  scale_fill_manual(values = colors)#+
  #xlab("Individual Sample") 


tmp <- ggplot_gtable(ggplot_build(bar_plot))
leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
legend <- tmp$grobs[[leg]]

bar_plot <- bar_plot +
  theme(legend.position = "none") + 
  ggtitle("FAMILY") + 
  theme(plot.title = element_text(size=45))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=20, fig.width=20}
plot_grid(legend)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=20, fig.width=20}
plot_grid(bar_plot)
```


# 3 different cut-offs - Individual cows

```{r, echo=FALSE, message=FALSE, warning=FALSE}
physeq_no_cont_trim_500 = prune_samples(sample_sums(physeq_no_cont)>=500, physeq_no_cont)

physeq_no_cont_trim_rel_500  = transform_sample_counts(physeq_no_cont_trim_500, function(x) x / sum(x) )

physeq_no_cont_trim_rel_500 = filter_taxa(physeq_no_cont_trim_rel_500, function(x) mean(x) > 0.025, TRUE)

physeq_no_cont_trim_rel_df_500 <- psmelt(physeq_no_cont_trim_rel_500)

physeq_no_cont_trim_rel_df_500 <- physeq_no_cont_trim_rel_df_500[!(grepl("LK", physeq_no_cont_trim_rel_df_500$Sample)), ]

physeq_no_cont_trim_rel_df_500$Read_cutoff <- 500



physeq_no_cont_trim_10000 = prune_samples(sample_sums(physeq_no_cont)>=10000, physeq_no_cont)

physeq_no_cont_trim_rel_10000  = transform_sample_counts(physeq_no_cont_trim_10000, function(x) x / sum(x) )

physeq_no_cont_trim_rel_10000 = filter_taxa(physeq_no_cont_trim_rel_10000, function(x) mean(x) > 0.025, TRUE)

physeq_no_cont_trim_rel_df_10000 <- psmelt(physeq_no_cont_trim_rel_10000)

physeq_no_cont_trim_rel_df_10000 <- physeq_no_cont_trim_rel_df_10000[!(grepl("LK", physeq_no_cont_trim_rel_df_10000$Sample)), ]

physeq_no_cont_trim_rel_df_10000$Read_cutoff <- 10000



physeq_no_cont_trim_rel_df_compare <- bind_rows(physeq_no_cont_trim_rel_df_500, physeq_no_cont_trim_rel_df_4000, physeq_no_cont_trim_rel_df_10000)

physeq_no_cont_trim_rel_df_compare$family <- factor(physeq_no_cont_trim_rel_df_compare$family, levels = c("Staphylococcaceae", "Peptostreptococcaceae", "Dermabacteraceae", "Beijerinckiaceae", "Streptococcaceae", "Erysipelotrichaceae", "Lachnospiraceae"))



physeq_no_cont_trim_rel_df_compare$Cow <- as.numeric(physeq_no_cont_trim_rel_df_compare$Cow)

physeq_no_cont_trim_rel_df_compare$Read_cutoff <- as.factor(physeq_no_cont_trim_rel_df_compare$Read_cutoff)

plots_list <- list()
legend_list <- list()
i <- 1

for (c in sort(unique(physeq_no_cont_trim_rel_df_compare$Cow)) ){

physeq_no_cont_trim_rel_df_plot <- physeq_no_cont_trim_rel_df_compare %>%
  group_by(Cow, Time_Injection, Sara, LPS, Abundance, family, Read_cutoff) %>%
  filter(Cow == c)


physeq_no_cont_trim_rel_df_plot$Time_Injection <- factor(physeq_no_cont_trim_rel_df_plot$Time_Injection, levels = c("1-Before", "32-Before", "32-After", "34-After"))

bar_plot <- ggplot() + geom_bar(
  aes(y = Abundance, x = Time_Injection, fill = family),
  data = physeq_no_cont_trim_rel_df_plot,
  stat = "identity" ,
  position = "dodge"
)  +labs(x="Category" , y= "Percentage (%)")+
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 20),
        #axis.text.x = element_blank(), 
        axis.text.y = element_text(size = 20), 
        strip.text.x = element_text(size = 30),
        strip.text.y = element_text(size = 30),
        axis.title.y = element_text(size = 36),
        axis.title.x = element_text(size = 36)) +
        #axis.title.x = element_blank()) + 
     facet_grid(Sara~LPS+Read_cutoff, scales = 'free_x')+
  ylab("Percentage of Sample") + 
  scale_fill_manual(values = colors)#+
  #xlab("Individual Sample") 


tmp <- ggplot_gtable(ggplot_build(bar_plot))
leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
legend <- tmp$grobs[[leg]]

bar_plot <- bar_plot +
  theme(legend.position = "none") + 
  ggtitle(paste("COW-",c, "-FAMILY", sep = "")) +
  theme(plot.title = element_text(size=45))

plots_list[[i]] <- bar_plot
legend_list[[i]] <- legend
 i <- i+1
}
```



```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=15, fig.width=20, results="asis"}
for (n in 1:length(plots_list)){
  plot(plot_grid(legend_list[[n]]))
  cat("\n\n\n")
  cat("\n\n\n")
  cat("\n\n\n")
  plot(plot_grid(plots_list[[n]]))
  cat("\n\n\n")
  cat("\\newpage")
}
```

