---
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(reshape2)
library(tidyverse)
library(printr)
```

## Taxonomic Assignment and Relative Abundance  
  
The table shows all taxa with a relative abundace of more than 0.05% across the entire dataset. The confidence value indicates the confidence in the taxonomic assignment. 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_count <-  read.csv("~/master/milk/milk-merge/dataflow/03-asv-table/feature-table-no-contam.txt", sep = "\t", header = TRUE, comment.char = "")
df_count <- df_count[rowSums(df_count[,2:ncol(df_count)]) > 3,]

df_count_melt <- melt(df_count, by = startsWith(colnames(df_count), "c"))
df_count_melt$variable <- NULL

df_count_melt <- df_count_melt %>%
  group_by(OTU.ID) %>%
  mutate(reads = sum(value)) %>%
  ungroup() %>%
  select(-value) %>%
  distinct() %>%
  mutate(total = sum(reads)) %>%
  mutate(rel_abundance = (reads / total)*100) %>%
  select(-reads, -total) %>%
  filter(rel_abundance > 0.05)

df_taxa <-  read.csv("~/master/milk/milk-merge/dataflow/03-asv-table/taxonomy.tsv", sep = "\t", header = TRUE, comment.char = "")
colnames(df_taxa) <- c("OTU.ID", "Taxon", "confidence")


df_taxa$Taxon <- gsub("D_.__", "", df_taxa$Taxon)

df_taxa  <- df_taxa %>%
  separate(Taxon , into = c("domain", "phylum", "class", "order", "family", "genus", "species"), sep = ";") %>%
  select(OTU.ID, family, genus, confidence)

df_final <- inner_join(df_taxa, df_count_melt)%>%
  arrange(desc(rel_abundance))

df_final$OTU.ID <- seq(1, nrow(df_final), 1) 




colnames(df_final) <- c("OTU", "Family", "Genus", "Confidence", "Relative Abundance")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_final
```
